# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'testWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testWidgetExtension

end

target 'widget_demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	 pod 'SnapKit'
	 pod 'Alamofire'

  target 'widget_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'widget_demoUITests' do
    # Pods for testing
  end

end
